apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: kiii
data:
  MONGO_INITDB_DATABASE: Blog-app

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: kiii
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4=

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  namespace: kiii
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_INITDB_DATABASE
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi